# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: bloccit_development
  encoding: unicode
  host: localhost

test:
  adapter: postgresql
  database: bloccit_test
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: bloccit_production
  encoding: unicode
